server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
   
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/users/**
          
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
          - Path=/hotels/**
          
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
          - Path=/ratings/**
#if you have more than one api like two more controllers having different apis in above path by giving comma we can add multiple
          
          
            
        